import '../../../data/models/quiz.dart';

abstract interface class QuizRepository {
  List<QuizTopic> topics();
}

/// Sample questions. Replace with an API / AI-generated quiz later.
/// Add more questions to any list: the counter ("02 / 10") follows the list.
class MockQuizRepository implements QuizRepository {
  const MockQuizRepository();

  @override
  List<QuizTopic> topics() => _topics;
}

const _topics = <QuizTopic>[
  // ------------------------------------------------------------------
  QuizTopic(
    id: 'js',
    title: 'JavaScript Core',
    subtitle: 'Arrays, operators, functions & async',
    category: QuizCategory.javascript,
    level: 'Beginner',
    fileName: 'snippet.js',
    langBadge: 'ES6+',
    questions: [
      QuizQuestion(
        tag: 'JS ARRAY METHODS',
        prompt: 'Which method is used to add one or more elements to the end of an array?',
        code: 'const items = [1, 2];\nitems.______(3); // [1, 2, 3]',
        options: ['push()', 'pop()', 'shift()', 'unshift()'],
        correctIndex: 0,
        hint: 'Think of pushing a new plate onto the top of a stack.',
        explanation: 'push() adds elements to the END of an array and returns the new length. unshift() adds to the front.',
        optionsAreCode: true,
      ),
      QuizQuestion(
        tag: 'JS VARIABLES',
        prompt: 'What does this code print?',
        code: 'let x = 5;\nx += 2;\nconsole.log(x);',
        options: ['5', '7', '52', 'undefined'],
        correctIndex: 1,
        hint: 'x += 2 means x = x + 2.',
        explanation: 'x starts at 5, then x += 2 makes it 7.',
        optionsAreCode: true,
      ),
      QuizQuestion(
        tag: 'JS ARRAY METHODS',
        prompt: 'Which method creates a NEW array by transforming every element?',
        code: 'const nums = [1, 2, 3];\nconst doubled = nums.______(n => n * 2);',
        options: ['map()', 'forEach()', 'filter()', 'reduce()'],
        correctIndex: 0,
        hint: 'It "maps" each value to a new value.',
        explanation: 'map() returns a new array with every element transformed. forEach() returns nothing.',
        optionsAreCode: true,
      ),
      QuizQuestion(
        tag: 'JS OPERATORS',
        prompt: 'What is the result of this expression?',
        code: "console.log('3' + 4);",
        options: ['7', '34', 'NaN', 'Error'],
        correctIndex: 1,
        hint: 'When one side is a string, + joins text instead of adding.',
        explanation: "With a string on one side, + joins text, so '3' + 4 becomes '34'.",
        optionsAreCode: true,
      ),
      QuizQuestion(
        tag: 'JS EQUALITY',
        prompt: 'What does the === operator compare?',
        options: ['Value only', 'Value and type', 'Type only', 'Memory address only'],
        correctIndex: 1,
        hint: 'It is called the "strict" equality operator.',
        explanation: "=== checks the value AND the type, with no conversion. So 5 === '5' is false.",
      ),
      QuizQuestion(
        tag: 'JS ASYNC',
        prompt: 'Which keyword pauses an async function until a Promise settles?',
        code: 'async function load() {\n  const data = ______ fetch(url);\n  return data;\n}',
        options: ['await', 'yield', 'defer', 'pause'],
        correctIndex: 0,
        hint: 'It "waits" for the result.',
        explanation: 'await pauses the async function until the Promise resolves, then gives you its value.',
        optionsAreCode: true,
      ),
    ],
  ),

  // ------------------------------------------------------------------
  QuizTopic(
    id: 'py',
    title: 'Python Basics',
    subtitle: 'Functions, lists, loops & dicts',
    category: QuizCategory.python,
    level: 'Beginner',
    fileName: 'snippet.py',
    langBadge: 'PY 3',
    questions: [
      QuizQuestion(
        tag: 'PY FUNCTIONS',
        prompt: 'Which keyword defines a function in Python?',
        code: "______ greet(name):\n    print('Hi', name)",
        options: ['def', 'func', 'function', 'lambda'],
        correctIndex: 0,
        hint: 'It is short for "define".',
        explanation: 'def starts a function definition. lambda only makes small anonymous functions.',
        optionsAreCode: true,
      ),
      QuizQuestion(
        tag: 'PY LISTS',
        prompt: 'What does len([1, 2, 3]) return?',
        options: ['2', '3', '4', 'Error'],
        correctIndex: 1,
        hint: 'Count the items inside the list.',
        explanation: 'len() returns how many items a list holds: 3.',
      ),
      QuizQuestion(
        tag: 'PY LOOPS',
        prompt: 'What does this loop print?',
        code: 'for i in range(3):\n    print(i)',
        options: ['0 1 2', '1 2 3', '0 1 2 3', '3'],
        correctIndex: 0,
        hint: 'range(3) starts at 0 and stops BEFORE 3.',
        explanation: 'range(3) produces 0, 1, 2. The stop value is never included.',
        optionsAreCode: true,
      ),
      QuizQuestion(
        tag: 'PY TYPES',
        prompt: 'Which of these types is mutable?',
        options: ['tuple', 'str', 'list', 'int'],
        correctIndex: 2,
        hint: 'You can append to it after creating it.',
        explanation: 'Lists can be changed in place. Tuples, strings and ints cannot.',
        optionsAreCode: true,
      ),
      QuizQuestion(
        tag: 'PY STRINGS',
        prompt: 'What does this print?',
        code: "s = 'hello'\nprint(s[1])",
        options: ['h', 'e', 'l', 'o'],
        correctIndex: 1,
        hint: 'Indexes start at 0, not 1.',
        explanation: "Index 0 is 'h', so s[1] is 'e'.",
        optionsAreCode: true,
      ),
      QuizQuestion(
        tag: 'PY DICTS',
        prompt: 'How do you read a missing key without raising a KeyError?',
        code: "age = user.______('age', 0)",
        options: ['get', 'fetch', 'read', 'find'],
        correctIndex: 0,
        hint: 'The method name is only three letters.',
        explanation: 'dict.get(key, default) returns the default instead of raising KeyError.',
        optionsAreCode: true,
      ),
    ],
  ),

  // ------------------------------------------------------------------
  QuizTopic(
    id: 'sql',
    title: 'SQL Essentials',
    subtitle: 'Queries, joins & aggregates',
    category: QuizCategory.sql,
    level: 'Beginner',
    fileName: 'query.sql',
    langBadge: 'SQL',
    questions: [
      QuizQuestion(
        tag: 'SQL FILTERING',
        prompt: 'Which clause filters rows?',
        code: 'SELECT * FROM users\n______ age > 18;',
        options: ['WHERE', 'ORDER BY', 'GROUP BY', 'LIMIT'],
        correctIndex: 0,
        hint: 'It sets a condition each row must meet.',
        explanation: 'WHERE keeps only the rows that match the condition.',
        optionsAreCode: true,
      ),
      QuizQuestion(
        tag: 'SQL SORTING',
        prompt: 'How do you sort from the highest score to the lowest?',
        code: 'SELECT name FROM scores\nORDER BY score ______;',
        options: ['ASC', 'DESC', 'TOP', 'DOWN'],
        correctIndex: 1,
        hint: 'It is short for "descending".',
        explanation: 'DESC sorts high to low. ASC (the default) sorts low to high.',
        optionsAreCode: true,
      ),
      QuizQuestion(
        tag: 'SQL JOINS',
        prompt: 'Which join returns only rows that match in BOTH tables?',
        code: 'SELECT u.name, o.total\nFROM users u\n______ orders o ON o.user_id = u.id;',
        options: ['INNER JOIN', 'LEFT JOIN', 'CROSS JOIN', 'FULL JOIN'],
        correctIndex: 0,
        hint: 'Think of the overlap in a Venn diagram.',
        explanation: 'INNER JOIN keeps only matching rows. LEFT JOIN keeps every row from the left table.',
        optionsAreCode: true,
      ),
      QuizQuestion(
        tag: 'SQL AGGREGATES',
        prompt: 'What does COUNT(*) return?',
        code: 'SELECT COUNT(*) FROM students;',
        options: ['The number of rows', 'The sum of a column', 'The largest value', 'The average'],
        correctIndex: 0,
        hint: 'It counts. It does not add values.',
        explanation: 'COUNT(*) returns how many rows are in the result.',
      ),
      QuizQuestion(
        tag: 'SQL DUPLICATES',
        prompt: 'Which keyword removes duplicate rows from the result?',
        code: 'SELECT ______ city FROM users;',
        options: ['DISTINCT', 'UNIQUE', 'DIFFERENT', 'ONLY'],
        correctIndex: 0,
        hint: 'It keeps each value only once.',
        explanation: 'SELECT DISTINCT returns each different value once.',
        optionsAreCode: true,
      ),
      QuizQuestion(
        tag: 'SQL GROUPING',
        prompt: 'Which clause filters groups AFTER GROUP BY?',
        code: 'SELECT dept, COUNT(*)\nFROM staff\nGROUP BY dept\n______ COUNT(*) > 5;',
        options: ['HAVING', 'WHERE', 'FILTER', 'LIMIT'],
        correctIndex: 0,
        hint: 'WHERE cannot use aggregate functions.',
        explanation: 'HAVING filters groups after aggregation. WHERE filters rows before grouping.',
        optionsAreCode: true,
      ),
    ],
  ),

  // ------------------------------------------------------------------
  QuizTopic(
    id: 'ds',
    title: 'Data Structures',
    subtitle: 'Stacks, queues, hashing & Big-O',
    category: QuizCategory.dataStructures,
    level: 'Intermediate',
    fileName: 'snippet.py',
    langBadge: 'PY',
    questions: [
      QuizQuestion(
        tag: 'STACKS',
        prompt: 'Which structure follows Last-In, First-Out (LIFO)?',
        options: ['Stack', 'Queue', 'Array', 'Binary tree'],
        correctIndex: 0,
        hint: 'Think of a pile of plates.',
        explanation: 'A stack removes the item added most recently. A queue is First-In, First-Out.',
      ),
      QuizQuestion(
        tag: 'QUEUES',
        prompt: 'Which structure follows First-In, First-Out (FIFO)?',
        options: ['Queue', 'Stack', 'Heap', 'Hash map'],
        correctIndex: 0,
        hint: 'Like people waiting in line.',
        explanation: 'A queue serves items in the order they arrived.',
      ),
      QuizQuestion(
        tag: 'BIG-O',
        prompt: 'What is the time complexity of binary search on a sorted array?',
        options: ['O(log n)', 'O(n)', 'O(1)', 'O(n²)'],
        correctIndex: 0,
        hint: 'Each step cuts the search space in half.',
        explanation: 'Binary search halves the range every step, so it takes O(log n) time.',
        optionsAreCode: true,
      ),
      QuizQuestion(
        tag: 'HASH MAPS',
        prompt: 'What is the average time to look up a key in a hash map?',
        options: ['O(1)', 'O(n)', 'O(log n)', 'O(n log n)'],
        correctIndex: 0,
        hint: 'The hash tells you exactly where to look.',
        explanation: 'A good hash function jumps straight to the right bucket: O(1) on average.',
        optionsAreCode: true,
      ),
      QuizQuestion(
        tag: 'RECURSION',
        prompt: 'What stops this recursion?',
        code: 'def fact(n):\n    if n == 0:\n        return 1\n    return n * fact(n - 1)',
        options: ['The n == 0 base case', 'The return keyword', 'The fact(n - 1) call', 'A for loop'],
        correctIndex: 0,
        hint: 'Every recursive function needs a case that does NOT call itself.',
        explanation: 'The base case (n == 0) returns without recursing, which ends the chain of calls.',
      ),
      QuizQuestion(
        tag: 'LINKED LISTS',
        prompt: 'How fast is inserting a new node at the HEAD of a linked list?',
        options: ['O(1)', 'O(n)', 'O(log n)', 'O(n²)'],
        correctIndex: 0,
        hint: 'You only change one pointer.',
        explanation: 'Inserting at the head just updates the head pointer: O(1).',
        optionsAreCode: true,
      ),
    ],
  ),
  // ------------------------------------------------------------------
  QuizTopic(
    id: 'dp',
    title: 'Dynamic Programming & Recursion',
    subtitle: 'Memoization, tabulation, Fibonacci & more',
    category: QuizCategory.dynamicProgramming,
    level: 'Advanced',
    fileName: 'snippet.py',
    langBadge: 'PY',
    questions: [
      QuizQuestion(
        tag: 'RECURSION',
        prompt: 'What is the base case of this function?',
        code: 'def fib(n):\n    if n <= 1:\n        return n\n    return fib(n - 1) + fib(n - 2)',
        options: ['n <= 1', 'fib(n - 1)', 'fib(n - 2)', 'return n'],
        correctIndex: 0,
        hint: 'Which line returns WITHOUT calling fib again?',
        explanation: 'When n <= 1 the function returns n directly, which stops the recursion.',
        optionsAreCode: true,
      ),
      QuizQuestion(
        tag: 'COMPLEXITY',
        prompt: 'What is the time complexity of the plain recursive fib(n) above?',
        options: ['O(2ⁿ)', 'O(n)', 'O(log n)', 'O(n²)'],
        correctIndex: 0,
        hint: 'Each call makes two more calls.',
        explanation: 'The call tree roughly doubles at every level, so the plain version is exponential: O(2ⁿ).',
        optionsAreCode: true,
      ),
      QuizQuestion(
        tag: 'MEMOIZATION',
        prompt: 'What does memoization do?',
        options: [
          'Caches results of calls so they are not recomputed',
          'Converts recursion into a loop with no extra memory',
          'Sorts the input before solving',
          'Splits the problem into equal halves',
        ],
        correctIndex: 0,
        hint: 'The word comes from "memo": write the answer down.',
        explanation: 'Memoization stores the result for each input, so overlapping subproblems are solved only once.',
      ),
      QuizQuestion(
        tag: 'TABULATION',
        prompt: 'Which approach builds the answer bottom-up from the smallest subproblems?',
        options: ['Tabulation', 'Memoization', 'Backtracking', 'Divide and conquer'],
        correctIndex: 0,
        hint: 'It fills a table, starting from the base cases.',
        explanation: 'Tabulation fills a table iteratively from the base cases up. Memoization works top-down.',
      ),
      QuizQuestion(
        tag: 'MEMOIZATION',
        prompt: 'Which line stores the result in the cache?',
        code: 'memo = {}\ndef fib(n):\n    if n in memo:\n        return memo[n]\n    if n <= 1:\n        return n\n    ______ = fib(n - 1) + fib(n - 2)\n    return memo[n]',
        options: ['memo[n]', 'memo', 'fib[n]', 'n[memo]'],
        correctIndex: 0,
        hint: 'The function returns memo[n] on the next line.',
        explanation: 'Saving into memo[n] lets later calls with the same n return immediately.',
        optionsAreCode: true,
      ),
      QuizQuestion(
        tag: 'DP BASICS',
        prompt: 'A problem is a good fit for dynamic programming when it has...',
        options: [
          'Overlapping subproblems and optimal substructure',
          'Only one possible solution',
          'No repeated work at all',
          'A sorted input',
        ],
        correctIndex: 0,
        hint: 'The same small problems keep showing up.',
        explanation: 'DP works when subproblems repeat (overlap) and the best answer is built from best sub-answers (optimal substructure).',
      ),
    ],
  ),
];
